### PR TITLE
HTTPS rather than HTTP

### PR DESCRIPTION
**Pull request by ryanstutes**
When doing a pip install on this package, I am getting a 403 SSL error.

```
  Downloading hotqueue-0.2.7.tar.gz
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.14.tar.gz
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-gP6cR4/hotqueue/setup.py", line 7, in <module>
        from distribute_setup import use_setuptools; use_setuptools()
      File "distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "distribute_setup.py", line 124, in _do_download
        to_dir, download_delay)
      File "distribute_setup.py", line 193, in download_setuptools
        src = urlopen(url)
      File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
        return opener.open(url, data, timeout)                                                                      
      File "/usr/lib/python2.7/urllib2.py", line 435, in open
        response = meth(req, response)
      File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
        'http', request, response, code, msg, hdrs)
      File "/usr/lib/python2.7/urllib2.py", line 473, in error
        return self._call_chain(*args)
      File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
        result = func(*args)
      File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
        raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
    urllib2.HTTPError: HTTP Error 403: SSL is required

    ----------------------------------------
```

Updating the `DEFAULT_URL` for the `distribute` package to use `https` rather than `http` fixes this issue.

### CODE REVIEW

**Comment by ryanstutes** [comment]
https://mail.python.org/pipermail/distutils-sig/2017-October/031712.html

**Comment by thanatos** [comment]
Sorry for the duplicate bug report; this commit (and a subsequent release) would fix #21.

**Comment by ryanstutes** [comment]
@thanatos No worries, I should have opened an issue alongside this PR.

**Comment by richardhenry** [comment]
Thanks for fixing this! Sorry I took so long to merge this PR.

**Comment by ryanstutes** [comment]
@richardhenry No problem! The [pypi package](https://pypi.python.org/pypi/hotqueue) is still at v2.7. Can you do a release so that I can point back to the package?

**Pull request merged**
